const SUCCESS_COLOR = '#43d787';
const FAVOURITE_COLOR = '#f766ad';
const WARNING_COLOR = '#ffbb00';
const CLOSED_COLOR = '#3598DB';

export { SUCCESS_COLOR, CLOSED_COLOR, FAVOURITE_COLOR, WARNING_COLOR };
